name: Build Plugin Jar

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build plugin
        run: ./gradlew build

      - name: Get version from Gradle
        id: version
        run: echo "VERSION=$(./gradlew -q printVersion)" >> $GITHUB_OUTPUT

      - name: Rename jar
        run: |
          mkdir output
          cp build/libs/*.jar output/SayanVanish-${{ steps.version.outputs.VERSION }}.jar

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*.jar
